# Generated by Django 5.0.1 on 2024-02-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_runway_runway_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='runway',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runway',
            name='runway_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runway',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
